# Generated by Django 4.1.3 on 2022-11-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('origin', models.CharField(choices=[('esi', 'ESI'), ('estin', 'ESTIN')], max_length=50)),
                ('elo', models.IntegerField()),
                ('motivation', models.TextField(max_length=150)),
            ],
        ),
    ]
