# Generated by Django 4.1.3 on 2022-11-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyant',
            old_name='anythingTOadd',
            new_name='anything_to_add',
        ),
    ]
